{% set name = "multi_json" %}
{% set version = "1.19.0" %}
{% set hash = "533a023cbcea2876fd19652c8eb9c5a38b821720369ef45a24c5cf70b293dffd" %}
{% set build = 0 %}

package:
  name: rb-{{ name|lower }}
  version: {{ version }}

source:
  url: https://rubygems.org/downloads/{{ name }}-{{ version }}.gem
  sha256: {{ hash }}

build:
  noarch: generic
  number: {{ build }}
  script:
    - gem install -N -l -V --norc --ignore-dependencies {{ name }}-{{ version }}.gem
    - gem unpack {{ name }}-{{ version }}.gem

requirements:
  host:
    - ruby
  run:
    - {{ pin_compatible('ruby', max_pin='x.x') }}

test:
  commands:
    - ruby -r {{ name }} -e 'exit 0'

about:
  home: https://rubygems.org/gems/multi_json
  license: MIT
  license_family: MIT
  license_file: LICENSE.md
  summary: |
    A common interface to multiple JSON libraries, including Oj, Yajl, the JSON gem (with C-extensions),
    the pure-Ruby JSON gem, NSJSONSerialization, gson.rb, JrJackson, and OkJson.
  doc_url: https://www.rubydoc.info/gems/multi_json
  dev_url: https://github.com/intridea/multi_json

extra:
  recipe-maintainers:
    - mxr-conda
    - sodre
    - jdmarques
