{% set name = "multi_json" %}
{% set version = "1.14.1" %}

package:
  name: rb-{{ name|lower }}
  version: {{ version }}

source:
  url: https://rubygems.org/downloads/{{ name }}-{{ version }}.gem
  sha256: d971296c0eacea289d31e4a7ab7ac5eda97262c62bbc8c110de4f5e36425c577

build:
  noarch: generic
  number: 0
  script:
    - gem install -N -l -V --norc --ignore-dependencies {{ name }}-{{ version }}.gem
    - gem unpack {{ name }}-{{ version }}.gem
  skip: {{ win }}

requirements:
  host:
    - ruby
  run:
    - ruby

test:
  commands:
    - ruby -r {{ name }} -e 'exit 0'

about:
  home: https://rubygems.org/gems/{{ name }}
  license: MIT
  license_family: MIT
  license_file: {{ name }}-{{ version }}/LICENSE.md
  summary: |
    A common interface to multiple JSON libraries, including Oj, Yajl, the JSON gem (with C-extensions),
    the pure-Ruby JSON gem, NSJSONSerialization, gson.rb, JrJackson, and OkJson.
  doc_url: https://www.rubydoc.info/gems/{{ name }}
  dev_url: https://github.com/intridea/{{ name }}

extra:
  recipe-maintainers:
    - benhuff
    - oblute
    - sodre
