travis:
  secure:
    BINSTAR_TOKEN: Wa3D6U01JVEavtYcCAZRMkQJEJevKItaZaHT47r0gk/KRFUAoj98qnw0wbzwa81K3Hs6OUuE764rOmjBxDZxfyH7X6wn5WAw+ZzwqHcN9ogmN6TzGldyzexEydDlgwJUQRtgl2lK1dv/m4IdYVm3L9OLRKzN7YDGxc1XmLj33oMdbI2tkZlaU+I+QiVnu+Mlwma8C87CWRIHoqXtLeoBO6QFFmuGfSbwPbDfTPPPFWPBlbHzIP7aBKjujb7IK0XU8xtOWHdiKrS9L0Ipo0pZmxyrL3Lln7QKJ+AJMzElNtKG1LnrZ0aKKLGW7YFw67gvofpAQ570QuyQTd4pInMhD/DrT0Uu8co6uANEczrp3uo+jwClBASgyAPUim0+fAauB6hfGrHad2qAmCTy21OtjXKeVimnSQd30dHlmE/gehEN9Nlnuvuvu3lF0hdWTv8OJsMIl185nBq5B14BG26X3L5cDXaFs/H3NViCjYf1ntXuF8NYYzewygF2ozYCctgVP7N6w6lvqm6ZhJYg97ElrFkgNVhpcYxOcpRVGF6Htu/u4xhCr4Q7/MjMl5d0THKJW6yfdoeep0tJyT/0x6h7L7674lM4IYcfcJTAF29bIcUYhxS2ILLJQ9KmMl264J4F4ysQ5b7Yto/78mHeo/pfuspgorabptgqwO1DYbX+Zcc=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
